<?php

namespace FreelancerTools\TimeTrackerBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * TimesliceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimesliceRepository extends EntityRepository
{
    public function getTimeslicesByProject($project) {
        $qb = $this->getEntityManager()->createQueryBuilder();   
        $qb
                ->select('s,p,a')
                ->from('FreelancerToolsTimeTrackerBundle:Timeslice', 's')
                ->leftJoin('s.activity', 'a')
                ->leftJoin('a.project', 'p')
                ->andwhere('p.id = :id')
                ->andwhere('a.archived = false')
                ->addOrderBy('s.startedAt', 'desc')
                ->setParameters(array(                    
                    ':id' => $project
                ))
        ;
        
        return $qb->getQuery()->execute();     
    }
}
