<?php

namespace FreelancerTools\CoreBundle\Entity;

use FreelancerTools\CoreBundle\Entity\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
    
}
